--liquibase formatted sql

--changeset simanov-an:create-db-changelog-1
--comment Create database
CREATE TABLE DEVICES_INFO
(
    ID VARCHAR (36) PRIMARY KEY,
    NAME VARCHAR (512)
);

CREATE TABLE WIFI_ANALYZE_REPORTS
(
    ID VARCHAR (36) PRIMARY KEY,
    CREATION_DATE TIMESTAMP,
    SSID VARCHAR (512),
    DEVICE_ID VARCHAR (36),
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES_INFO(ID)
);
CREATE INDEX I_WARS_CD_SSID ON WIFI_ANALYZE_REPORTS(SSID, CREATION_DATE)

--rollback;