--liquibase formatted sql

--changeset simanov-an:create-db-changelog-1
--comment Create database
CREATE TABLE DEVICES_INFO
(
    ID VARCHAR (36) PRIMARY KEY,
    NAME VARCHAR (512) NOT NULL
);

CREATE TABLE WIFI_ANALYZE_REPORTS
(
    ID VARCHAR (36) PRIMARY KEY,
    CREATION_DATE TIMESTAMP NOT NULL,
    DEVICE_ID VARCHAR (36) NOT NULL,
    FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES_INFO(ID)
);
CREATE INDEX I_WARS_CD ON WIFI_ANALYZE_REPORTS(CREATION_DATE);

CREATE TABLE WIFI_ANALYZES_INFO
(
    ID VARCHAR (36) PRIMARY KEY,
    CREATION_DATE TIMESTAMP NOT NULL,
    SSID VARCHAR (512) NOT NULL,
    WIFI_REPORT_ID VARCHAR (36) NOT NULL,
    FOREIGN KEY (WIFI_REPORT_ID) REFERENCES WIFI_ANALYZE_REPORTS(ID)
);
CREATE INDEX I_WAI_CD_SSID ON WIFI_ANALYZES_INFO(SSID, CREATION_DATE);

--rollback;