spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wifi_analyzer
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: wifi_analyzer
    password: 1234
    hikari:
      connectionTimeout: 30000
      idle-timeout: 60000
      max-lifetime: 120000
      auto-commit: false
      minimum-idle: 2
      maximum-pool-size: 5
      pool-name: HikariDataSourcePool
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false